### ISSUE TITLE
Package is not auto-updated on Packagist

### ISSUE THREAD

**Issue by kdambekalns** [gesagtgetan/GesagtGetan.CookieDialogue#5]
The recently tagged  4.4.1 (thanks!) is not available on https://packagist.org/packages/gesagtgetan/cookiedialogue and Packagist says: _This package is not auto-updated._

I clicked the "update now" link, but you might want to fix this. https://packagist.org/about#how-to-update-packages

**Comment by gerhard-boden** [comment]
Hey Karsten, thanks for letting us know! Just fixed the webhook and the first test looks promising!
